production:
  adapter: postgresql
  encoding: utf8
  database: <%= ENV['DB_NAME'] %>
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  timeout: 5000
  port: 5432
